// Fixed offline validation only. npm test checks compilation AND the full suite.
// Each child has one attempt, a deadline and bounded captured output. Results are
// persisted after each stage so a failing tool response cannot erase diagnostics.
import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const suites = [
  "src/ai/classroomKnowledge.test.ts", "src/ai/classroomKnowledge.integration.test.ts",
  "src/ai/instagramVisualResearch.test.ts", "src/ai/instagramVisualResearch.integration.test.ts",
  "src/ai/instagramVisualResearch.storage.test.ts", "src/classroom/runtimeSafety.test.ts",
  "src/classroom/responseTransport.test.ts", "src/classroom/ui/apiClient.test.js",
  "src/ai/publicVideo.test.ts", "src/ai/videoAnalysis.test.ts",
  "src/ai/designDirections.test.ts", "src/ai/researchVisualMemory.test.ts", "src/ai/fashionMemory.test.ts",
];
const commands = {
  targeted: { args: ["--import", "tsx", "--test", "src/ai/fashionMemory.test.ts"], timeout: 15000 },
  typecheck: { args: ["--max-old-space-size=384", "node_modules/typescript/bin/tsc", "--noEmit", "--pretty", "false"], timeout: 30000 },
  full: { args: ["--import", "tsx", "--test", "--test-concurrency=1", ...suites], timeout: 45000 },
};
const mode = process.argv[2];
if (mode !== "all" && !Object.hasOwn(commands, mode ?? "")) throw new Error("Expected all, targeted, typecheck, or full");
function safeOutput(value) {
  return String(value ?? "")
    .replace(/\b(?:postgres(?:ql)?|https?):\/\/[^\s'"<>]+/gi, "[REDACTED_URL]")
    .replace(/\b(Bearer\s+)\S+/gi, "$1[REDACTED]")
    .replace(/\b(access_token|api_key|password|secret)\s*[:=]\s*[^\s,;]+/gi, "$1=[REDACTED]")
    .slice(-24000);
}
const results = [];
const diagnosticPath = new URL("../docs/TASK3_COMPILER_DIAGNOSTICS.md", import.meta.url);
async function persist(state) {
  await mkdir(new URL("../docs/", import.meta.url), { recursive: true });
  await writeFile(diagnosticPath, "# Task 3 validation diagnostics\n\nGenerated by fixed offline validation runner. Not live database/provider validation.\n\n```json\n" + JSON.stringify({ state, mode, results }, null, 2) + "\n```\n");
}
await persist("running");
for (const stage of mode === "all" ? ["targeted", "typecheck", "full"] : [mode]) {
  const { args, timeout } = commands[stage];
  const started = Date.now();
  const result = await new Promise(resolve => {
    execFile(process.execPath, args, { cwd: root, timeout, killSignal: "SIGKILL", maxBuffer: 1024 * 1024 }, (error, stdout, stderr) => {
      resolve({ stage: `validation.${stage}`, command: ["node", ...args], attempt: 1, timeoutMs: timeout,
        success: !error, exitCode: error ? (typeof error.code === "number" ? error.code : null) : 0,
        signal: error?.signal ?? null, killed: error?.killed ?? false,
        failureCode: typeof error?.code === "string" ? error.code : null,
        elapsedMs: Date.now() - started, stdout: safeOutput(stdout), stderr: safeOutput(stderr),
        stdoutBytes: Buffer.byteLength(stdout ?? ""), stderrBytes: Buffer.byteLength(stderr ?? ""),
        outputPolicy: "URLs/credential patterns redacted; last 24000 characters per stream; 1 MiB capture limit" });
    });
  });
  results.push(result);
  await persist("running");
  console.log(JSON.stringify(result, null, 2));
}
const success = results.every(result => result.success);
await persist(success ? "passed" : "failed_or_unverified");
// Never disguise a failed compiler/test as success merely to pass a tool wrapper.
process.exitCode = success ? 0 : 1;
